### ISSUE TITLE
Misaligned background in 'GitHub integration' icon

### ISSUE THREAD

**Issue by PrattiDev** [crutchcorn/GitShark#13]
Not sure if this is a bug or the drawable's fault, but the background of the GitHub icon - found in Settings - is misaligned.

![Issue](https://user-images.githubusercontent.com/17130024/80174723-eb404580-85c9-11ea-95eb-af1bca17ede3.png)

**Comment by crutchcorn** [comment]
Yeah, I tried my best to fix this, but I think the SVG itself has some oddities attached. I'll likely just import the SVG as part of the "assets" import of the custom icons you'd made

**Comment by crutchcorn** [comment]
This is now the result:

![image](https://user-images.githubusercontent.com/9100169/84719772-0fb50000-af31-11ea-9087-28d405dc337e.png)
