### ISSUE TITLE
Navigation bar does not respect dark mode

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/GitShark#6]
Currently, in dark mode, we do not change the color of the navbar.

![Preview with the broken navbar](https://user-images.githubusercontent.com/9100169/79033928-26249100-7b67-11ea-8e6e-44214082fb3a.png)

This is because we're blocked upstream:

https://github.com/thebylito/react-native-navigation-bar-color/issues/23

The app repetitively crashes upon implementing the code that _should_ work in https://github.com/crutchcorn/GitShark/tree/crashing_nav_bar

**Comment by coin3x** [comment]
The problem seems to be that Android doesn't support abbreviated color notations like `#FFF`.

`react-native-navigation-bar-color` internally uses `Color.parseColor()` from Android API.

From the [Android docs](https://developer.android.com/reference/android/graphics/Color#parseColor(java.lang.String)):
> ## Color.parseColor
> Parse the color string, and return the corresponding color-int. If the string cannot be parsed, throws an IllegalArgumentException exception. Supported formats are:
> - #RRGGBB
> - #AARRGGBB

**Comment by crutchcorn** [comment]
@coin3x that's a great observation! You might want to make a PR upstream that adds support to the package for tri-digit shorthand, as it seems to be stumping folks upstream even:

https://github.com/thebylito/react-native-navigation-bar-color/issues/23

**Comment by crutchcorn** [comment]
Closing this issue in favor of #9 (since having a transparent navbar solves the issue of a solid colored navbar not matching).

I will be leaving the branch up since it's linked upstream until such time that the upstream issue has been resolved
